name: Deploy Demo to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./Leaflet.Polydraw/demo/package-lock.json"

      - name: Install main package dependencies
        run: npm ci
        working-directory: ./Leaflet.Polydraw

      - name: Build main package
        run: npm run build
        working-directory: ./Leaflet.Polydraw

      - name: Install demo dependencies
        run: npm ci
        working-directory: ./Leaflet.Polydraw/demo

      - name: Build demo
        run: npm run build
        working-directory: ./Leaflet.Polydraw/demo

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./Leaflet.Polydraw/demo/dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
